--- sound/soc/msm/qdsp6v2/Makefile
+++ sound/soc/msm/qdsp6v2/Makefile
@@ -2,7 +2,7 @@
 			msm-compress-q6-v2.o msm-compr-q6-v2.o msm-multi-ch-pcm-q6-v2.o \
 			msm-pcm-lpa-v2.o msm-pcm-afe-v2.o msm-pcm-voip-v2.o \
 			msm-pcm-voice-v2.o msm-dai-q6-hdmi-v2.o \
-			msm-lsm-client.o
+			msm-lsm-client.o msm-audio-effects-q6-v2.o
 obj-$(CONFIG_SND_SOC_QDSP6V2) += snd-soc-qdsp6v2.o msm-pcm-dtmf-v2.o \
 				 msm-dai-stub-v2.o
 obj-$(CONFIG_DOLBY_DAP) += msm-dolby-dap-config.o
